name: Generate Newsletter

on:
  schedule:
    # Schedule to run daily at 7 AM UTC+2 (German time during CEST)
    - cron: '0 5 * * *'  # Adjust based on daylight saving time
  push:
    branches:
      - main

jobs:
  generate-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Generate newsletter
        shell: bash  # You can choose pwsh or cmd as needed
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_PASS: ${{ secrets.REDDIT_PASS }}
          REDDIT_USER: ${{ secrets.REDDIT_USER }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASS: ${{ secrets.ZOHO_PASS }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          python main.py
      
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          git add newsletter.md  # Replace with your output file if different
          git commit -m "Update newsletter" || echo "No changes to commit"
          git push
